### PR TITLE
Lyrics command

### PR DESCRIPTION
**Pull request by hatry4**
I created lyrics command using genius api i edited .env, config.ts, locale/EnglishUS.json and added Lyrics.ts

For the other languages well i can't add because it's too many to translate.

image
image

I'm not familar doing the locales but i tried my best to put it in to the lyrics command.

### CODE REVIEW

**Comment by infnibor** [comment]
@hatry4 fix 
image

**Review by infnibor — COMMENTED** [review]
Delete $ witg "${lyrics}"

**Comment by hatry4** [comment]
is this correct? @infnibor

**Comment by infnibor** [comment]
> is this correct? @infnibor

Nope, Take into account all the pictures, because this 2 version is correct from the screnna only, and what as a review I did in the language files you do not need to use $, because as you execute the command it will execute, but there will be an unprompted character

**Comment by hatry4** [comment]
> > is this correct? @infnibor
> 
> Nope, Take into account all the pictures, because this 2 version is correct from the screnna only, and what as a review I did in the language files you do not need to use $, because as you execute the command it will execute, but there will be an unprompted character
>
> How about i remove the locale or language in the lyrics command because i really don't understand how the locale settings works

**Comment by infnibor** [comment]
> @infnibor
> 
> > Co powiesz na to, że usunę ustawienia regionalne lub język w poleceniu lyrics, ponieważ naprawdę nie rozumiem, jak działają ustawienia regionalne

It is good as it is at the moment, if you fix what lint biome blew up it should work, although I would depend a little on fine-tuning the command, because it does not fully work correctly, I checked on another song than you gave, which on the genius site has lyrics, and it hit that the lyrics for this song was not found. so something does not quite 100% work

**Comment by infnibor** [comment]
> My lyrics command is far better

A bit pointless comment, you are commenting on someone's work that he has done, maybe there is a command a bit to refine, but if something does not suit you then you can always add your own as PR if you twer believe that yours is better. This PR is not for stating opinions about the code that we don't even see and about the introduction and refinement of a new command to the project.

**Comment by hatry4** [comment]
> Co powiesz na to, że usunę ustawienia regionalne lub język w poleceniu lyrics, ponieważ naprawdę nie rozumiem, jak działają ustawienia regionalne

may I ask Which song your trying to get maybe it not published into the genius lyrics? that why

**Comment by infnibor** [comment]
> > Co powiesz na to, że usunę ustawienia regionalne lub język w poleceniu lyrics, ponieważ naprawdę nie rozumiem, jak działają ustawienia regionalne
> 
> czy mogę zapytać, którą piosenkę próbujesz dostać, może nie została opublikowana w genialnym tekście? Z tego powodu

I checked, the song has its reflection in genius, but the command twerds that it does not - song https://www.youtube.com/watch?v=4IwqHYcYEQA, reflection in geniushttps://genius.com/Kuqe-2115-taki-may-ja-lyrics, I also checked on other cases the same thing, your song works, but the others already too much at least as I test not.

**Comment by hatry4** [comment]
I recently tested a feature that allows me to play random Indian music and view the lyrics. While I can get lyrics from Spotify using a link, I have trouble accessing lyrics for music videos on YouTube (not YouTube Music). To enhance this experience, I plan to add a dedicated lyrics page for longer lyrics.

**Comment by hatry4** [comment]
https://cdn.discordapp.com/attachments/909355699392356384/1282094777466228786/staff-commands___Hatry4_Development_-_Discord_2024-09-08_05-38-35.mp4?ex=66de1b4f&is=66dcc9cf&hm=5c558c236997d0126fd63830a7bb34f75dc283a80efe0aeac4ecf829891e1096&

https://cdn.discordapp.com/attachments/909355699392356384/1282095032215666761/bots___Panais_-_Community_-_Discord_2024-09-08_05-45-18.mp4?ex=66de1b8b&is=66dcca0b&hm=dd7d96fd93805077a74fbee36a6d076fa517983e236e7fe6f26e444c8d926329&

@infnibor Check this out id compare my test bot with panais and we are having the same problem.

**Pull request merged**
