### PR TITLE
Update locales, packages and setup system


### PR DESCRIPTION
**Pull request by hwangsihu**
I'm so sorry for asking so many pull requests. I forgot I hadn't committed this.

### CODE REVIEW

**Comment by hwangsihu** [comment]
I working on a fix for the Setup System. Don't push yet.. I think it would be better to fix this and push it together. I don't want to close the pull request and increase the number. I'll edit the title when it's all done.

**Comment by hwangsihu** [comment]
Done. I worked with the app so it's one file per commit. Please understand. And the button order looks the best this way i think...

**Comment by LucasB25** [comment]
> Je travaille sur un correctif pour le système de configuration. Ne le faites pas encore... Je pense qu'il serait préférable de corriger cela et de le mettre en place. Je ne veux pas fermer la demande d'extraction et augmenter le nombre. Je modifierai le titre quand tout sera terminé.

I don't see any fixes in what you did, just change buttons.

**Comment by hwangsihu** [comment]
Well... I've been trying to fix something, but I keep failing, so I guess I'll have to put it off. So I just fixed the mismatched buttons. I was trying to fix the queue loss issue that occurs when you play a previous song.

**Comment by LucasB25** [comment]
image
The "lint" returns you so many errors?

**Pull request merged**
