### PR TITLE
Update

### PR DESCRIPTION
**Pull request by hwangsihu**

### CODE REVIEW

**Comment by infnibor** [comment]
Bad lavalink config

**Comment by hwangsihu** [comment]
What?

**Comment by infnibor** [comment]
> What?

If you want to edit it, read the documentation carefully, arl is commented out by default and so are its options, the Android client has long been broken and is not used instead of Android Test Suite, and the fact that in the YouTube plugin repo you have the clients listed in this order does not mean that you have to set it that way, you set it according to your own applications.

**Comment by LucasB25** [comment]
Your PR will remain open for a while, lavalink changes are not officially published yet

**Comment by hwangsihu** [comment]
ok

**Comment by LucasB25** [comment]
@hwangsihu Please split its modification lavalink to another PR

**Comment by hwangsihu** [comment]
> @hwangsihu수정된 lavalink를 다른 PR로 분할해주세요.

What do you mean

**Comment by infnibor** [comment]
> > @hwangsihu수정된 lavalink를 다른 PR로 분할해주세요.
> 
> What do you mean
Changes regarding incorrect version of skybot plugin in other new PR

**Comment by hwangsihu** [comment]
Do you mean #696?

**Comment by infnibor** [comment]
> Do you mean #696?

Yea

**Comment by hwangsihu** [comment]
Haha, it looks like the repository is gone

**Comment by hwangsihu** [comment]
It's already at 1.7.0, so should I revert it back to the original?
It's already at 1.7.0, so should I revert it back to the original?

**Comment by infnibor** [comment]
> It's already at 1.7.0, so should I revert it back to the original?

Fix by https://github.com/appujet/lavamusic/pull/697 - less translation, and you have the correction right away, the issue of PR consolidation.

**Comment by hwangsihu** [comment]
Ok

**Comment by hwangsihu** [comment]
Is it okay to commit like this?

**Comment by hwangsihu** [comment]
Is there a reason to be set in config.ts? I only use it as YouTube, so I will be pushed here every time I commit something.

**Comment by LucasB25** [comment]
do as you did create problems in the requests

**Comment by infnibor** [comment]
I would recommend closing this PR, and bot info unnecessarily throwing away the work of the App, regarding downloading variables from language files, making millions of unnecessary commits - you test locally at your place and make any corrections, because then over 20 commits go to the repo, and most of the changes are pointless if you don't know the meaning and documentation

**Comment by infnibor** [comment]
In short, the clearer it is, the better for the recipient - a pending commit has a description of what has been changed and, of course, sometimes it happens that corrections are needed, but then either you amend the commit or at least describe it properly, because then 10 commits mean ".". I have no complaints, I just try to make the changes clear even for other contributors, etc.

**Pull request closed without merging**
