### PR TITLE
Update and Translation fix

### PR DESCRIPTION
**Pull request by hwangsihu**
There is no problem here, and nothing has changed other than making the rules easier to see in the Biome case.

### CODE REVIEW

**Comment by LucasB25** [comment]
Take me your change biom

**Comment by hwangsihu** [comment]
What? You want me to tell you what changed? If that's the case, then I just Sort rules in alphabetical order and changed the schema version.

**Comment by hwangsihu** [comment]
Oh, is this inconvenient?
And you don't need to set sorcemap to false in tsconfig.json. Just remove that line.

**Comment by LucasB25** [comment]
why remove shard ?

**Comment by LucasB25** [comment]
image

Stop making changes and look

**Comment by hwangsihu** [comment]
Hmm, I removed it to make it run faster since it seems like there aren't many bots with many servers, but I'll rollback it later if you want.

**Comment by LucasB25** [comment]
Lavamusic is there for everyone, not just you...

**Comment by appujet** [comment]
i can't accept your PR 

i told you don't change anything in [biome.json](https://github.com/appujet/lavamusic/pull/734/commits/1b5e0844cf732ad1d8ab16c67f12a0d8805792d6#diff-2bc8a1f5e9380d5a187a4e90f11b4dd36c3abad6aea44c84be354a4f44cdec55)

also you delete https://github.com/appujet/lavamusic/pull/734/commits/1b5e0844cf732ad1d8ab16c67f12a0d8805792d6#diff-16cffbe1da5eb8e51110c127ed8e9570861a221d68cf79b47cf67ba323ad0170

https://github.com/appujet/lavamusic/pull/734/commits/1b5e0844cf732ad1d8ab16c67f12a0d8805792d6#diff-f9426dddc0f7d499d9726435beb96830b5d5d00f64e6cbcca0273674292bbc02

**Comment by hwangsihu** [comment]
Since I made one commit, can you please tell me which file needs to be rolled back?

**Pull request closed without merging**
