### PR TITLE
Update

### PR DESCRIPTION
**Pull request by hwangsihu**

### CODE REVIEW

**Review by appujet — CHANGES_REQUESTED** [review]
YouTube is broken some time YouTubeMusic is good

**Comment by infnibor** [comment]
> YouTube is broken some time YouTubeMusic is good

Not quite - the default youtube source from lava Player is outdated and broken, but instead there is a youtube source plugin, which is just a rewritten official plugin replacing the old youtube source and even in the configuration you have enable search: true to search with yt search. In case of errors on the lavalink side it is a matter of skillful application.yml setting - I have it set correctly and everything works normally including youtube search. Once in Lavalink support one of the co-creators of lavalink said that searching via ytm search does not make sense, because yt search itself will already give these results, which is why in the official documentation there are only 2 main providers for lavasrc.  2nd issue, maybe not related to the source but to the translation of the bot, in the Setup System command itself there is no single line thrown under the translation system "Nothing playing for now" when you just create a setup channel, by default instead of downloading from the language files it always displays this text and from the Uttils.ts file at the very end of the file there is also 1 line not converted to download from the translation system + my fixing commit went as one of the last so I will have to release a commit overwriting several languages ​​that were added or modified in the meantime, because unfortunately my fixing changes are not applied there.

**Comment by hwangsihu** [comment]
We went looking everywhere, but couldn’t find those commits.
Sometimes commits can disappear after a force-push. Head back to the latest changes here.

**Comment by LucasB25** [comment]
Re create a request  by updating your repo please

**Comment by hwangsihu** [comment]
What's the problem?

**Comment by hwangsihu** [comment]
Oh my, why was the Japanese edited?

**Pull request closed without merging**
