### PR TITLE
Update

### PR DESCRIPTION
**Pull request by hwangsihu**

### CODE REVIEW

**Comment by infnibor** [comment]
@hwangsihu The translation files you added are incorrect because they are all in English.

**Comment by infnibor** [comment]
And don't add senseless changes to lavalink configuration if you don't know how to use them (read comments on youtube plugin optional config) in short it's an optional configuration for more advanced users and it's not recommended to use it without knowledge about it

**Comment by infnibor** [comment]
The same with removing Lava-search in the comment in the official documentation and I think it's even there that lava search is required

**Comment by LucasB25** [comment]
> And don't add senseless changes to lavalink configuration if you don't know how to use them (read comments on youtube plugin optional config) in short it's an optional configuration for more advanced users and it's not recommended to use it without knowledge about it
> 
> ```
>     # ---------------- WARNING ----------------
>     # This part of the config is for DEMONSTRATION PURPOSES ONLY!
>     # Do NOT use this config before understanding what the options do.
>     # You do NOT need to copy this config just because it is published here.
>     # ---------------- WARNING ----------------
> ```

it’s not the first time I’ve refused her this change

**Comment by infnibor** [comment]
> > And don't add senseless changes to lavalink configuration if you don't know how to use them (read comments on youtube plugin optional config) in short it's an optional configuration for more advanced users and it's not recommended to use it without knowledge about it
> > ```
> >     # ---------------- WARNING ----------------
> >     # This part of the config is for DEMONSTRATION PURPOSES ONLY!
> >     # Do NOT use this config before understanding what the options do.
> >     # You do NOT need to copy this config just because it is published here.
> >     # ---------------- WARNING ----------------
> > ```
> 
> it’s not the first time I’ve refused her this change

You also need to restore the lavasrc plugin otherwise it will cause an error at startup
``` youtube: true # Enable YouTube search source (https://github.com/topi314/LavaSearch)
```

**Comment by hwangsihu** [comment]
Haha, I made a mistake while copying the YouTube plugin settings.

**Comment by infnibor** [comment]
@hwangsihu 
Cool that you added a new language variation, but you would still change the code, because they are the same and should not be :) (And see to the repo of languages, because it was reported to want a language with PT code and some others)
```
    // [Locale.PortugueseBR]: “🇧🇷”,
    // [Locale.PortuguesePT]: “🇧🇷”,
```
image

And 2 thing as you already edit ReadME then put the correct link to lavalink, because it is still on the old author, theoretically it redirects GitHub itself, but it is better to give the correct one right away, as you already edit that one anyway.
From: (https://github.com/freyacodes/Lavalink)
To: (https://github.com/lavalink-devs/Lavalink)

**Comment by hwangsihu** [comment]
@infnibor Oh man, I just saw this message and edited it.

**Pull request merged**
