### PR TITLE
Update Steal.ts

### PR DESCRIPTION
**Pull request by Beelzebub2**
i believe the suggested fix works, command behaved as normal

### CODE REVIEW

**Comment by LucasB25** [comment]
image
 show

**Comment by Beelzebub2** [comment]
what are you using to get those suggestions? @LucasB25

**Comment by LucasB25** [comment]
> what are you using to get those suggestions? @LucasB25

npm run lint

**Comment by LucasB25** [comment]
@Beelzebub2 
image
fix

**Pull request merged**
